name: Surface Hardware
version: "0.2.2"
slug: surface_hardware
description: Surface Pro hardware monitoring and control

arch:
  - amd64

startup: services
boot: auto

init: false

privileged:
  - SYS_ADMIN

devices:
  - /sys/class/backlight:/sys/class/backlight
  - /sys/class/power_supply:/sys/class/power_supply
  - /sys/class/thermal:/sys/class/thermal
