name: Surface Hardware

version: "0.2.1"

slug: surface_hardware

description: Surface Pro hardware monitoring and control

arch:
  - amd64

startup: services

boot: auto

init: false

privileged:
  - SYS_ADMIN

devices:
  - /sys:/sys

services:
  - mqtt:need
