name: Surface Hardware
version: "0.1.0"
slug: surface_hardware

description: Surface Pro hardware monitoring

arch:
  - amd64

startup: services
boot: auto

privileged:
  - SYS_ADMIN

devices:
  - /sys:/sys
